module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Especificación',
      link: null,
      items: [{ type: 'autogenerated', dirName: 'specification' }],
    },
    {
      type: 'category',
      label: 'Producto',
      items: [{ type: 'autogenerated', dirName: 'product' }],
    },
  ],
};
